global:
  proxy:
    no_proxy: ""
    http_proxy: ""
    https_proxy: ""
  keeppvc: false

replicaCount: 1

modeldownload:
  name: model-download
  image:
    registry: "intel/"
    tag: rc3_2026.0
    pullPolicy: IfNotPresent

  readinessProbe:
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 60
      periodSeconds: 30
    
  env:
    HUGGINGFACEHUB_API_TOKEN: ""
    GETI_WORKSPACE_ID: ""
    GETI_HOST: ""
    GETI_TOKEN: ""
    GETI_SERVER_API_VERSION: "v1"
    GETI_SERVER_SSL_VERIFY: "False"
    ENABLED_PLUGINS: "all"   #Comma separated list of plugins to enable, or "all"

  service:
    type: NodePort
    nodePort: 
    port: 8000
